-- MySQL Script generated by MySQL Workbench
-- Mon Mar 25 14:15:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `genero_preferido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Livro` (
  `idLivro` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `ano_publicação` VARCHAR(45) NULL,
  `idDono` INT NOT NULL,
  PRIMARY KEY (`idLivro`),
  INDEX `fk_Livro_Usuario_idx` (`idDono` ASC) VISIBLE,
  CONSTRAINT `fk_Livro_Usuario`
    FOREIGN KEY (`idDono`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Troca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Troca` (
  `idTroca` INT NOT NULL,
  `livro_oferecido` INT NOT NULL,
  `livro_desejado` INT NOT NULL,
  `idUsuario_1` INT NOT NULL,
  `idUsuario_2` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`idTroca`),
  INDEX `fk_Troca_Livro1_idx` (`livro_oferecido` ASC) VISIBLE,
  INDEX `fk_Troca_Livro2_idx` (`livro_desejado` ASC) VISIBLE,
  INDEX `fk_Troca_Usuario1_idx` (`idUsuario_1` ASC) VISIBLE,
  INDEX `fk_Troca_Usuario2_idx` (`idUsuario_2` ASC) VISIBLE,
  CONSTRAINT `fk_Troca_Livro1`
    FOREIGN KEY (`livro_oferecido`)
    REFERENCES `mydb`.`Livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Troca_Livro2`
    FOREIGN KEY (`livro_desejado`)
    REFERENCES `mydb`.`Livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Troca_Usuario1`
    FOREIGN KEY (`idUsuario_1`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Troca_Usuario2`
    FOREIGN KEY (`idUsuario_2`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avaliação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avaliação` (
  `idAvaliação` INT NOT NULL,
  `avaliação_nota` INT NOT NULL,
  `comentario` VARCHAR(45) NULL,
  `idTroca` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idAvaliação`),
  INDEX `fk_Avaliação_Troca1_idx` (`idTroca` ASC) VISIBLE,
  INDEX `fk_Avaliação_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Avaliação_Troca1`
    FOREIGN KEY (`idTroca`)
    REFERENCES `mydb`.`Troca` (`idTroca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliação_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
