-- MySQL Script generated by MySQL Workbench
-- Mon Mar 25 12:21:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipamento` (
  `idEquipamento` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descrição` VARCHAR(45) NOT NULL,
  `disponibilidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEquipamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Material` (
  `idMaterial` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preço` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `idCompra` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idEquipamento` INT NOT NULL,
  `idMaterial` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preço_total` FLOAT NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `fk_Compra_Usuario_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Compra_Equipamento1_idx` (`idEquipamento` ASC) VISIBLE,
  INDEX `fk_Compra_Material1_idx` (`idMaterial` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Equipamento1`
    FOREIGN KEY (`idEquipamento`)
    REFERENCES `mydb`.`Equipamento` (`idEquipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Material1`
    FOREIGN KEY (`idMaterial`)
    REFERENCES `mydb`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agendamento_maquina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agendamento_maquina` (
  `idAgendamento` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idEquipamento` INT NOT NULL,
  `idMaterial` INT NOT NULL,
  `data_inicial` DATETIME NOT NULL,
  `data_final` DATETIME NOT NULL,
  PRIMARY KEY (`idAgendamento`),
  INDEX `fk_Agendamento_maquina_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Agendamento_maquina_Equipamento1_idx` (`idEquipamento` ASC) VISIBLE,
  INDEX `fk_Agendamento_maquina_Material1_idx` (`idMaterial` ASC) VISIBLE,
  CONSTRAINT `fk_Agendamento_maquina_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agendamento_maquina_Equipamento1`
    FOREIGN KEY (`idEquipamento`)
    REFERENCES `mydb`.`Equipamento` (`idEquipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agendamento_maquina_Material1`
    FOREIGN KEY (`idMaterial`)
    REFERENCES `mydb`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `idCurso` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descrição` VARCHAR(200) NOT NULL,
  `data_hora` DATETIME NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `idEvento` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descrição` VARCHAR(200) NOT NULL,
  `data_hora` DATETIME NOT NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
