-- MySQL Script generated by MySQL Workbench
-- Mon Mar 25 13:35:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  `dispositivo_favorito` VARCHAR(45) NULL,
  `ultimo_acesso` DATETIME NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Perfil` (
  `idPerfil` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `nome_perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil`),
  INDEX `fk_Perfil_Usuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Perfil_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conteudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conteudo` (
  `idConteudo` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `sinopse` VARCHAR(250) NOT NULL,
  `elenco` VARCHAR(200) NOT NULL,
  `classificação` VARCHAR(45) NOT NULL,
  `lançamento` DATE NOT NULL,
  `disponibilidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idConteudo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lista_reproducao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lista_reproducao` (
  `idLista_reproducao` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLista_reproducao`),
  INDEX `fk_Lista_reproducao_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Lista_reproducao_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assistidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assistidos` (
  `idAssistidos` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idConteudo` INT NOT NULL,
  `data_acesso` DATETIME NOT NULL,
  PRIMARY KEY (`idAssistidos`),
  INDEX `fk_Assistidos_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Assistidos_Conteudo1_idx` (`idConteudo` ASC) VISIBLE,
  CONSTRAINT `fk_Assistidos_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Assistidos_Conteudo1`
    FOREIGN KEY (`idConteudo`)
    REFERENCES `mydb`.`Conteudo` (`idConteudo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dispositivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dispositivos` (
  `idDispositivos` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `nome_dispositivo` VARCHAR(45) NOT NULL,
  `tipo_dispositivo` VARCHAR(45) NOT NULL,
  `ultimo_acesso` DATETIME NOT NULL,
  PRIMARY KEY (`idDispositivos`),
  INDEX `fk_Dispositivos_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Dispositivos_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recomendacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recomendacoes` (
  `idRecomendacoes` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idConteudo` INT NOT NULL,
  `nota_recomendação` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRecomendacoes`),
  INDEX `fk_Recomendacoes_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Recomendacoes_Conteudo1_idx` (`idConteudo` ASC) VISIBLE,
  CONSTRAINT `fk_Recomendacoes_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recomendacoes_Conteudo1`
    FOREIGN KEY (`idConteudo`)
    REFERENCES `mydb`.`Conteudo` (`idConteudo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
