-- MySQL Script generated by MySQL Workbench
-- Mon Mar 25 13:48:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artista` (
  `idArtista` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descrição` VARCHAR(250) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArtista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projetos` (
  `idProjetos` INT NOT NULL,
  `idArtista` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descrição` VARCHAR(250) NOT NULL,
  `objetivo` VARCHAR(450) NOT NULL,
  `valor_arrecadado` VARCHAR(45) NOT NULL,
  `data_limite` DATETIME NOT NULL,
  PRIMARY KEY (`idProjetos`),
  INDEX `fk_Projetos_Artista_idx` (`idArtista` ASC) VISIBLE,
  CONSTRAINT `fk_Projetos_Artista`
    FOREIGN KEY (`idArtista`)
    REFERENCES `mydb`.`Artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recompensa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recompensa` (
  `idRecompensa` INT NOT NULL,
  `idProjetos` INT NOT NULL,
  `decrição` VARCHAR(200) NOT NULL,
  `valor_minimo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRecompensa`),
  INDEX `fk_Recompensa_Projetos1_idx` (`idProjetos` ASC) VISIBLE,
  CONSTRAINT `fk_Recompensa_Projetos1`
    FOREIGN KEY (`idProjetos`)
    REFERENCES `mydb`.`Projetos` (`idProjetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contribuicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contribuicao` (
  `idContribuicao` INT NOT NULL,
  `idProjetos` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  `data` DATETIME NOT NULL,
  `idUsuario` INT NULL,
  PRIMARY KEY (`idContribuicao`),
  INDEX `fk_Contribuicao_Projetos1_idx` (`idProjetos` ASC) VISIBLE,
  INDEX `fk_Contribuicao_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Contribuicao_Projetos1`
    FOREIGN KEY (`idProjetos`)
    REFERENCES `mydb`.`Projetos` (`idProjetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contribuicao_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
