-- MySQL Script generated by MySQL Workbench
-- Mon Mar 25 14:03:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereço` (
  `idEndereço` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idEndereço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agricultor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agricultor` (
  `idAgricultor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `area_cultivada` VARCHAR(45) NOT NULL,
  `tipo_cultura` VARCHAR(45) NOT NULL,
  `idEndereço` INT NOT NULL,
  PRIMARY KEY (`idAgricultor`),
  INDEX `fk_Agricultor_Endereço_idx` (`idEndereço` ASC) VISIBLE,
  CONSTRAINT `fk_Agricultor_Endereço`
    FOREIGN KEY (`idEndereço`)
    REFERENCES `mydb`.`Endereço` (`idEndereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Drone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Drone` (
  `idDrone` INT NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `autonomia` VARCHAR(45) NOT NULL,
  `alcance` VARCHAR(45) NOT NULL,
  `capacidade` VARCHAR(45) NOT NULL,
  `preço_por_hora` FLOAT NOT NULL,
  PRIMARY KEY (`idDrone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serviço` (
  `idServiço` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `descrição` VARCHAR(450) NULL,
  `preço_hora` FLOAT NULL,
  PRIMARY KEY (`idServiço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluguel` (
  `idAluguel` INT NOT NULL,
  `idAgricultor` INT NOT NULL,
  `idDrone` INT NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_final` DATETIME NOT NULL,
  `valor_total` FLOAT NOT NULL,
  `Aluguelcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idAluguel`),
  INDEX `fk_Aluguel_Agricultor1_idx` (`idAgricultor` ASC) VISIBLE,
  INDEX `fk_Aluguel_Drone1_idx` (`idDrone` ASC) VISIBLE,
  CONSTRAINT `fk_Aluguel_Agricultor1`
    FOREIGN KEY (`idAgricultor`)
    REFERENCES `mydb`.`Agricultor` (`idAgricultor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluguel_Drone1`
    FOREIGN KEY (`idDrone`)
    REFERENCES `mydb`.`Drone` (`idDrone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Drone_serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Drone_serviço` (
  `idDrone_serviço` INT NOT NULL,
  `idDrone` INT NOT NULL,
  `idServiço` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDrone_serviço`),
  INDEX `fk_Drone_serviço_Drone1_idx` (`idDrone` ASC) VISIBLE,
  INDEX `fk_Drone_serviço_Serviço1_idx` (`idServiço` ASC) VISIBLE,
  CONSTRAINT `fk_Drone_serviço_Drone1`
    FOREIGN KEY (`idDrone`)
    REFERENCES `mydb`.`Drone` (`idDrone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Drone_serviço_Serviço1`
    FOREIGN KEY (`idServiço`)
    REFERENCES `mydb`.`Serviço` (`idServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
